### ISSUE TITLE
Script slows down FL

### ISSUE THREAD

**Issue by desiremusic** [soundwrightpro/FLNI_KK#5]
When the script is running, faders and send knobs in playlist freezes and stutters.
I know it's because of the script because when I turn off M32 it returns to normal.

I also run another script for Launchkey61 maybe both of them running makes the FL slow down, I don't know. But when I only using launchkey script, this wasn't the case.

I am also using i9 9900k and 64gb of ram, so I don't think specs are the issue. Running FL on 4K.

**Comment by soundwrightpro** [comment]
Thanks, @desiremusic for the report. I'm working on threading/multitreading to overcome these issues.  The solution I have now only works on MacOS; I'm just waiting for ImageLine to address some issues on Windows. Is the Launchkey61 a user script? Please send link to your source. Thank you!

**Comment by desiremusic** [comment]
Yes! Here's the link: https://github.com/MiguelGuthridge/Novation-LaunchKey-Mk2-Script

**Comment by soundwrightpro** [comment]
Was addressed in version 5.0.5, but 5.0.6 had to disable it as it wasn't stable on Windows. Currently awaiting a fix from Image-Line. 20.8 looks like they addressed the issue. When resolved it will be included in the new feature set.
