### ISSUE TITLE
Better way to pick sounds from browser and dropping them to channel rack

### ISSUE THREAD

**Issue by desiremusic** [soundwrightpro/FLNI_KK#6]
It's a great feature to browse sounds without touching the mouse but it can be better in my opinion:

Only one click instead of double-click to select folders/sounds
Dropping sound into channel rack is only available via right-click menu by choosing open in new channel, but it is creating other problems: 
1) every channel you opened stays on the screen until you close them one by one 
2) you have to use shift + 4d button to get back to the browser because it automatically switches to channel rack
A solution for problem 2 might be, using a different shortcut to focus the browser as you did on plugin picker (shift + double-click 4D)

So there can be a better way to get the sounds into the channel rack without using the right-click menu or "open in new channel"

Thanks.

**Comment by soundwrightpro** [comment]
It's a limitation of python in FL Studio. Currently, the first click always registers in the double click option. To avoid this, there is no single-click option to avoid any potential problems. If it ever changes, it will be in the new feature set.
