### ISSUE TITLE
Can't get back to Komplete Kontrol VST after switching to FL control

### ISSUE THREAD

**Issue by desiremusic** [soundwrightpro/FLNI_KK#7]
How to recreate:

- Open FL
- Script is working okay
- Load Komplete Kontrol as new vst to channel rack
- Keyboard recognizes Komplete Kontrol and lights up the browser, scale & arp buttons
- Choose browser a select a sound
- To get back to the script (to control FL Studio again) press "TRACK INSTANCE" 
- Now keyboard controls channel rack
- You can't get back to Komplete Kontrol which you've opened you have to add a new Komplete Kontrol plugin

**Comment by soundwrightpro** [comment]
Hi @desiremusic, thanks for the issue report, but this isn't an issue. Please take a moment to look over the README located here: https://github.com/soundwrightpro/FLNI_KK. The section for this starts with" if the Komplete Control Plugin (not to be confused with the Application)..." will aid you with switching modes.
